version: '3.8'

services:
  app:
    build: .
    container_name: nextjs-app
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
