version: '3.9'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./prisma/dev.db

volumes:
  prisma_data:
