import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';

import Sidebar from '../components/sidebar/sidebar';
import ContextMenuProvider from './context/context-menu';
import SidebarConextProvider from './context/sidebar-conext';

import { SWRProvider } from '@/provider/swr-provider';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SWRProvider>
        <body className={montserrat.className}>
          <main className="flex">
            <ContextMenuProvider>
              <SidebarConextProvider>
                <Sidebar />
              </SidebarConextProvider>
            </ContextMenuProvider>
            {children}
          </main>
        </body>
      </SWRProvider>
    </html>
  );
}
